### PR TITLE
minor improvements: 9p/version

### PR DESCRIPTION
**Pull request by minad**
* version class removed, instatiation is unnecessary. just use the constants directly
* 9p memory usage improved by sharing strings
* config samples update

### CODE REVIEW

**Comment by wolfmanjm** [comment]
Why are you changing unrelated things? the version stuff is unrelated and should not be included in this pull request It is also unnecessary changes that do not fix anything. They need to be separated from this pull request, and submitted separately if at all.

**Comment by minad** [comment]
Sorry. This is really not necessary to be included here. This is more of a stylistic change and I had to do it when I saw this abuse of classes. Pull it if you want ;)

I am currently reworking some things in the 9p fs. So it would be so or so better if I reopen this later again.

**Comment by wolfmanjm** [comment]
Please refrain from making stylistic changes without consulting first. Or put them in a separate pull request. Style is a matter of taste and our tastes obviously differ. In this case I see the simplification so would appreciate it as a separate pull request marked style change. Thanks

**Comment by wolfmanjm** [comment]
Also as  A matter of git etiquette you should not request a pull of something that is still under heavy development. It is preferable to keep it in a branch until you think it is ready for prime time then request a pull. doing frequent updates of a pull makes it hard to maintain, and revert if necessary. Just FYI :)

**Comment by minad** [comment]
Yes, this is some matter of style. I meant it also as some kind of constructive critism for you :) It is less effort for me to just send you the request instead of consulting first about such minor things. You don't have to take it and I think one can work very efficiently together like this.

Ok, I try to send the pull requests in more coarse intervals. I usually try to send the pull requests when I finished some feature or change, but probably you prefer to have it as a whole larger pull request?

**Comment by wolfmanjm** [comment]
For a feature like this you can work on a branch, and add to the branch as you go. Once it is finished then request it be merged. You can issue a pull request for a branch that you are still working on, but request that the pull request not be merged until you are ready. The recent z probe stuff qharely did it was a pull request for months before he was satisfied and asked for it to be merged.
As described in the github section of the wiki, all pull requests need to be related to a single feature or a bug fix, and different things needs to be in separate pull requests. We try to follow the gitflow protocol for git at this time.

**Pull request closed without merging**
