### PR TITLE
Full graphics suport for the RRDGLCD

### PR DESCRIPTION
**Pull request by unlimitedbacon**
This is a resubmission of @garikdan's PR https://github.com/Smoothieware/Smoothieware/pull/1368.

I also fixed a bug with his code (text character sometimes were not drawn correctly) and removed the temporary workaround for incomplete graphics support.

IMG_20190712_105703~2

### CODE REVIEW

**Comment by wolfmanjm** [comment]
does this replace PR #1393

**Comment by unlimitedbacon** [comment]
No. This makes the new watch screen work on the RRDGLCD. It also means that if https://github.com/Smoothieware/Smoothieware/pull/1393 is merged it will work on both the RRDGLCD and the Viki.

**Comment by wolfmanjm** [comment]
Sorry for the delay. I finally got around to testing this and it seems to work fine. Thank you

**Comment by wolfmanjm** [comment]
This breaks things like jog screen and setting temp screens, the lines do not update. It has been reverted.

**Pull request merged**
