### PR TITLE
fix progress when large files are being played

### PR DESCRIPTION
**Pull request by wolfmanjm**
addresses Issue #1255

### CODE REVIEW

**Comment by obujor** [comment]
Hi,
in my opinion to prevent 32 integer overflow we can just rewrite the expression in another way.
This is the original line:
`unsigned int pcnt = (file_size - (file_size - played_cnt)) * 100 / file_size;`

The factor causing integer overflow is _100_ because _file_size_ will hardly be so big to overflow integer, that will be a file of about 4GB of size, almost 200 milions of line of code.

So I think instead of using _float_ we can write the expression that way (using less memory than float):
`unsigned int pcnt = (file_size - (file_size - played_cnt)) / file_size * 100;`

And thus the factor which may cause overflow could be only _file_size_ but for reasons listed above this is very difficult to happen even because I don't think smoothie supports huge files of about 4GB.

I hope this can be helpful.

**Comment by triffid** [comment]
That's not how integer division works. It'll always return zero unless played_cnt gets larger than file_size.

Since this operation doesn't need much precision, why not do something like `unsigned pcnt = played_cnt / (file_size / 100)` as long as file_size is larger than a megabyte or so?

**Comment by obujor** [comment]
Oh yes, you're right, it's been a while since I did not write C* code.
I like your solution.

**Comment by wolfmanjm** [comment]
I already fixed it with a float (which is the same size as an int anyway).

**Comment by obujor** [comment]
> which is the same size as an int anyway

I was not aware of this, sorry for my  useless comments.

**Comment by karabas** [comment]
As I see on LCD Display percentage  does not work correctly. It somewhere overflows after about 40 hours of printing and starts from zero. I think LCD code was not changed.
I think we need something similar with percent_complete
```
void Player::on_get_public_data(void *argument)
{
    PublicDataRequest *pdr = static_cast<PublicDataRequest *>(argument);

    if(!pdr->starts_with(player_checksum)) return;

    if(pdr->second_element_is(is_playing_checksum) || pdr->second_element_is(is_suspended_checksum)) {
        static bool bool_data;
        bool_data = pdr->second_element_is(is_playing_checksum) ? this->playing_file : this->suspended;
        pdr->set_data_ptr(&bool_data);
        pdr->set_taken();

    } else if(pdr->second_element_is(get_progress_checksum)) {
        static struct pad_progress p;
        if(file_size > 0 && playing_file) {
            p.elapsed_secs = this->elapsed_secs;
  //          p.percent_complete = (this->file_size - (this->file_size - this->played_cnt)) * 100 / this->file_size;
			p.percent_complete = (((float)this->file_size - (this->file_size - this->played_cnt)) * 100.0F) / this->file_size;
            p.filename = this->filename;
            pdr->set_data_ptr(&p);
            pdr->set_taken();
        }
    }
}

```

**Pull request merged**
