### PR TITLE
add echo command to shell commands

### PR DESCRIPTION
**Pull request by luc-github**
as discussed in https://github.com/Smoothieware/Smoothieware/issues/1396

### CODE REVIEW

**Comment by wolfmanjm** [comment]
Thank you. I merged this.

I was wondering if the ```echo: ``` is really needed I'd really like to keep this compliant with the linux command echo, which would just echo the parameters.

If you do not object I'll remove the ```echo: ``` from the reply.

**Comment by luc-github** [comment]
I put it to be compliant with M118 and to avoid Sender to be disturbed by anything send from Serial as they are supposed to ignore lines start by `echo:` (I think)

**Comment by wolfmanjm** [comment]
Ok I'll leave it as it is then. (BTW none of the senders I know of ignore echo: they may ignore ECHO: and they usually ignore // )

**Comment by luc-github** [comment]
Thank you ^_^

**Pull request merged**
