### PR TITLE
Feature/prevent cold extrusion

### PR DESCRIPTION
**Pull request by irrenhaus**
I finally found some time to do more work on this. This is part of my entry of the Smoothie Contest.

This is the cold extrusion prevention: It should prevent a 3D printer from doing extruder moves when the corresponding hotend temperature is below a specified point. This should prevent one from letting the printer run while anything is wrong with it's heaters or sensors.

As discussed with @wolfmanjm some time ago, this functionality should be built as a module so that its resource usage does not hit people who don't want to use this.

This module allows multiple instances to be configured - one for each extruder. Each instance will do one public data request to its configured temperature controller every 2 seconds.

There is one single thing I'm not happy about regarding the code: The ON_HALT event takes its time until the extruder motor actually gets disabled. This means that the extruder motor will do at least a part of a move before it's killed.
I did not find any better way to do this without adding new public data requests to the extruder module and without having public data requests in the on_gcode_execute callback. If anyone knows a better way to kill the extruder instantly, please let me know it.

However, it should work well enough to do what it's intended for: Kill the printer before doing too much if there is any problem with the heating elements and/or sensors.

PS: Is the Smoothie contest actually still running? Haven't heard a thing since some months :)

### CODE REVIEW

**Comment by arthurwolf** [comment]
+Nils hey. Contest still running, just have not had time to answer
everybody.

On Sun, May 24, 2015 at 3:40 PM, Nils Hesse <notifications@github.com>
wrote:

> I finally found some time to do more work on this. This is part of my
> entry of the Smoothie Contest.
>
> This is the cold extrusion prevention: It should prevent a 3D printer from
> doing extruder moves when the corresponding hotend temperature is below a
> specified point. This should prevent one from letting the printer run while
> anything is wrong with it's heaters or sensors.
>
> As discussed with @wolfmanjm <https://github.com/wolfmanjm> some time
> ago, this functionality should be built as a module so that its resource
> usage does not hit people who don't want to use this.
>
> This module allows multiple instances to be configured - one for each
> extruder. Each instance will do one public data request to its configured
> temperature controller every 2 seconds.
>
> There is one single thing I'm not happy about regarding the code: The
> ON_HALT event takes its time until the extruder motor actually gets
> disabled. This means that the extruder motor will do at least a part of a
> move before it's killed.
> I did not find any better way to do this without adding new public data
> requests to the extruder module and without having public data requests in
> the on_gcode_execute callback. If anyone knows a better way to kill the
> extruder instantly, please let me know it.
>
> However, it should work well enough to do what it's intended for: Kill the
> printer before doing too much if there is any problem with the heating
> elements and/or sensors.
>
> PS: Is the Smoothie contest actually still running? Haven't heard a thing
> since some months :)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Smoothieware/Smoothieware/pull/667
> Commit Summary
>
>    - First work on the cold extrusion prevention
>    - This is at least compiling, still not tested yet
>    - Trying to get this to work, a lot of debug writes which are never
>    called...
>    - Working cold extrusion prevention
>    - Merge branch 'edge' into feature/prevent_cold_extrusion_as_module
>    - Remove forgotten reference
>
> File Changes
>
>    - *A* ConfigSamples/Snippets/cold_extrusion_prevention.config
>    <https://github.com/Smoothieware/Smoothieware/pull/667/files#diff-0>
>    (3)
>    - *M* src/main.cpp
>    <https://github.com/Smoothieware/Smoothieware/pull/667/files#diff-1>
>    (6)
>    - *A* src/modules/utils/security/ColdExtrusionPrevention.cpp
>    <https://github.com/Smoothieware/Smoothieware/pull/667/files#diff-2>
>    (201)
>    - *A* src/modules/utils/security/ColdExtrusionPrevention.h
>    <https://github.com/Smoothieware/Smoothieware/pull/667/files#diff-3>
>    (40)
>    - *A* src/modules/utils/security/SecurityPool.cpp
>    <https://github.com/Smoothieware/Smoothieware/pull/667/files#diff-4>
>    (19)
>    - *A* src/modules/utils/security/SecurityPool.h
>    <https://github.com/Smoothieware/Smoothieware/pull/667/files#diff-5>
>    (18)
>
> Patch Links:
>
>    - https://github.com/Smoothieware/Smoothieware/pull/667.patch
>    - https://github.com/Smoothieware/Smoothieware/pull/667.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/pull/667>.
>



-- 
Courage et bonne humeur.

**Comment by wolfmanjm** [comment]
Why is it called SecurityPool? I am not liking that name, it does not describe or have anything to do with cold extrusion prevention IMO. So will cause mass confusion for future developers who will think it has something to do with login security or something.

**Comment by arthurwolf** [comment]
Possibly you want to rename it to "safetypool" ? Or "safetymeasurepool" ?

On Sun, May 24, 2015 at 8:34 PM, Jim Morris <notifications@github.com>
wrote:

> Why is it called SecurityPool? I am not liking that name, it does not
> describe or have anything to do with cold extrusion prevention IMO. So will
> cause mass confusion for future developers who will think it has something
> to do with login security or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/pull/667#issuecomment-105046599>
> .
>



-- 
Courage et bonne humeur.

**Comment by irrenhaus** [comment]
Yeah you're right, SafetyPool would have been a better name. I was thinking about having multiple of the features my contest entry was about in this pool and the word "security" came first to mind, but safety is more correct.
I'll go on and rename it then.

@arthurwolf No worries because of the contest, just wanted to ask because I was not sure :)

**Comment by wolfmanjm** [comment]
calling ON_HALT is the wrong thing to do. It is not designed to be used for this kind of temporary condition.
I suggest setting a flag in the associated extruder to enable or disable the extruder. ON_Halt basically is an emergency shutdown which this is really not.

**Comment by wolfmanjm** [comment]
To expound a bit,  Cold extrude is not an emergency condition, its sole purpose is to not engage the extruder motor if the hotend is not yet up to temp. This is how Marlin uses it So if yo try to extrude nothing happens, and should print out a console message message saying something like cold extrude prevention. Once the hotend is up to temp then extrudes will be allowed without further action from the user.

It is debatable whether if during a print you should abort the print if temp drops below a certain temp. This IMO is a totally different scenario to cold extrusion prevention. In this case one would return !! to the host which will stop/pause the upstream host from sending any more gcode. And allow the user to resume once the issue is resolved.

**Comment by irrenhaus** [comment]
@wolfmanjm Yeah I see, I'll revisit this then and rewrite it to set a flag on the extruder. Thanks!

**Comment by wolfmanjm** [comment]
this has been too long in the queue. Reopen if updated and suggested fixes are made.

**Comment by trgtylcnky** [comment]
I know this is not a forum platform but I want to ask if this feature exists in the current versions. It does not prevent any cold extrusion in my printer.

**Comment by Dark-3agle** [comment]
I have a similar issue. I don't want my printer to do cold extrusion by itself. I want to enable it in my config file. Is it possible?
Also, there are patches for my issue above. Can I use them? If I can, then how?
Thanks.

**Comment by Dark-3agle** [comment]
these are the errors I'm facing.
Compiling modules/utils/safety/ColdExtrusionPrevention.cpp
modules/utils/safety/ColdExtrusionPrevention.cpp: In member function 'void ColdExtrusionPrevention::on_config_reload(void*)':
modules/utils/safety/ColdExtrusionPrevention.cpp:40:44: error: 'class Kernel' has no member named 'temperature_control'
     auto&availableControllers = THEKERNEL->temperature_control->get_controllers();
                                            ^
modules/utils/safety/ColdExtrusionPrevention.cpp:47:20: error: unable to deduce 'auto&&' from 'availableControllers'
     for(auto ctrl: availableControllers) {
                    ^
modules/utils/safety/ColdExtrusionPrevention.cpp: At global scope:
modules/utils/safety/ColdExtrusionPrevention.cpp:111:40: error: 'argument' was not declared in this scope
     Gcode* gcode = static_cast<Gcode*>(argument);
                                        ^
modules/utils/safety/ColdExtrusionPrevention.cpp:115:5: error: expected unqualified-id before 'if'
     if(!gcode->has_g || !gcode->has_letter('E')) {
     ^
modules/utils/safety/ColdExtrusionPrevention.cpp:121:5: error: expected unqualified-id before 'if'
     if(!read_flag(FLAG_TEMP_OK) && !read_flag(FLAG_WAS_KILLED)) {
     ^
modules/utils/safety/ColdExtrusionPrevention.cpp:124:1: error: expected declaration before '}' token
 }
 ^
make[2]: *** [../LPC1768/./modules/utils/safety/ColdExtrusionPrevention.o] Error 1

can someone help?

**Comment by wolfmanjm** [comment]
This was closed a while ago as it is no longer compatible with the source code tree, that is why you get errors. It would take some work to get it to compile again.

**Comment by Dark-3agle** [comment]
Ok, Sir.
Can you suggest any methods where I can get this feature to work?
Smoothie by default enables cold extrusion, but I want to disable it and
enable it only when required.
Can it be done by modifying the existing source codes?  Or should I Start
writing new code?
Thanks,
Rahul.

**Pull request closed without merging**
