### PR TITLE
Update predefined_thermistors.h

### PR DESCRIPTION
**Pull request by Fourmi**
Add "Hisens 104F400 " thermistor steinhart value for hotend "Simple ONE" et "All In ONE"

### CODE REVIEW

**Comment by wolfmanjm** [comment]
I think this is misnamed, does not appear to be hisens specific. I also do not fond this to be common,y available. please provide a link to a common reseller.
 did find reference to a 104F4000 but does not mention hisens.

**Comment by Fourmi** [comment]
Ok,i see why Hisens is not appear because there are changed name .
Now it's Musor 
You can read the specs of thermistor here >https://drive.google.com/file/d/0B0eJVP0Swfx5WXczQ1QwZ09Kd2s/view?usp=sharing

Thx arthur

**Comment by wolfmanjm** [comment]
then rename it it NTC104F4000

**Comment by Fourmi** [comment]
Ok,i renamed it
Thx

**Comment by arthurwolf** [comment]
Is this clean enough to be merged ? If so tell me so I add the thermistor to the documentation.

**Comment by wolfmanjm** [comment]
as far as i can see it is a very rare thermistor and no one uses it, so it didn't seem worth adding. Especially as anyone actually having one and using it could simply add the data in config.

**Pull request closed without merging**
