### PR TITLE
Download dfu-util automatically during install on Windows

### PR DESCRIPTION
**Pull request by DavidJRobertson**
Following from #1220

I have removed the binary `dfu-util.exe` and instead modified `win_install.cmd` to download a copy on install.

### CODE REVIEW

**Comment by wolfmanjm** [comment]
I am still not happy with downloading windows binaries from shady sources due to viruses.
I'd prefer to leave it as instructions on the wiki and allow people to risk downloading executables for windows at their discretion.

**Comment by DavidJRobertson** [comment]
I'm unsure why downloading dfu-util is any different in that regard to downloading gcc. 

The file is checked against an MD5 in the install script so if the file available at that URL were to change in the future, it would cause the script to fail.

**Comment by DavidJRobertson** [comment]
I have added installation instructions to the wiki: http://smoothieware.org/compiling-smoothie#flashing-via-dfu-usb-device-firmware-update

However, the makefile will still have to be adjusted to replace the call to cp with one to copy.

**Comment by DavidJRobertson** [comment]
#1223

**Pull request closed without merging**
