### PR TITLE
Feature/abc axis

### PR DESCRIPTION
**Pull request by wolfmanjm**
Add A B C axis to gcode parser.

In order to use there should be no extruders defined.
The new axis are defined using...

```
# A axis
delta_steps_per_mm                    100     # may be steps per degree for example
delta_step_pin                               xx              # Pin for delta stepper step signal
delta_dir_pin                                xx             # Pin for delta stepper direction
delta_en_pin                                 xx             # Pin for delta enable
delta_current                                1.5              # Z stepper motor current
delta_max_rate                               300.0            # mm/min
delta_acceleration                          500.0            # mm/sec²

# B axis
epsilon_steps_per_mm                    100     # may be steps per degree for example
epsilon_step_pin                              xx              # Pin for delta stepper step signal
epsilon_dir_pin                                xx             # Pin for delta stepper direction
epsilon_en_pin                                xx             # Pin for delta enable
epsilon_current                                1.5              # Z stepper motor current
epsilon_max_rate                               300.0            # mm/min
epsilon_acceleration                          500.0            # mm/sec²

# C axis
zeta_steps_per_mm                    100     # may be steps per degree for example
zeta_step_pin                               xx              # Pin for delta stepper step signal
zeta_dir_pin                                xx             # Pin for delta stepper direction
zeta_en_pin                                 xx             # Pin for delta enable
zeta_current                                1.5              # Z stepper motor current
zeta_max_rate                               300.0            # mm/min
zeta_acceleration                          500.0            # mm/sec²
```

The firmware must be compiled with `make AXIS=6` or `make AXIS=4` depending on how many axis are needed. (Use minimum needed).

`get pos` will show the A B C axis positions

`G28.3 A0 B0 C0` will set the axis to the specified values (sort of manual homing)

**NOTE** that the parameters passed into A B or C in a G0 or G1 are raw, they do not go through the arm solution, they are the values that will be passed to the stepper based on steps_per_mm for that axis (although it may be interpreted as steps per degree for instance).

This may not be a complete solution, the planner treats  X Y Z as primary axis, A B C are not treated as primary axis, there is no junction deviation applied to them for instance, and if they move a significant number of steps more than X Y Z there may be speed issues.

### CODE REVIEW

**Comment by arthurwolf** [comment]
Just wanted to say : awesome !

**Comment by cojarbi** [comment]
@wolfmanjm Im back and ready to test my rotary with the laser. Can you help me with a compile? im using a compatible smoothie ( azsmz ) Thanks

**Comment by wolfmanjm** [comment]
@cojarbi right now this does not support laser. I need to merge this with the new-laser branch. Once I do that it will be ready for testing, but the new-laser branch needs to be tested first, and no one has reported having tested it. The one report I got of it not working made no sense as the part that was reported as not working had not been changed. I am still waiting to hear if the master branch worked for that case (I suspect not).

**Comment by cojarbi** [comment]
@wolfmanjm Ok so ill do that first. The brach is add/new-laser?

**Comment by wolfmanjm** [comment]
@cojarbi yes, but there is a prebuilt binary you can test, it was in Peters G+ post

**Comment by cojarbi** [comment]
First rotation test https://youtu.be/4vA-SCcFs24 . Still i need to figure out how to calculate the correct steps for this

**Comment by wolfmanjm** [comment]
@cojarbi it will be steps/degree, but you use the steps_per_mm config to set it. SHoul dbe fairly easy to set, most steppers are 200*micro_steps per 360° multiply by any gearing you have and divide by 360 and you have steps per degree.

**Comment by wolfmanjm** [comment]
Currently the ABC axis can only be set via config. Once it is working I'll add M92, M203.1 etc for A B C axis. (and any other relevant M codes, including support for M500).

**Comment by andySigler** [comment]
@wolfmanjm just tested and works great. I found `G28A` and `G28B` commands seem to break the firmware. You've mentioned using `G28.3` to assign the current position as `0`, however are the A,B,C axis setup to be able to use endstop switches to formally home?

**Comment by wolfmanjm** [comment]
@andySigler No homing is not supported at the moment. only G28.3 is supported.

**Comment by wolfmanjm** [comment]
this is being replaced by a merge with the PR #1037 currently being tested in branch https://github.com/wolfmanjm/Smoothie/tree/merge-abc-with-homing

**Comment by sularman** [comment]
Need help,
want to know how to displaying A B C axis position on lcd
trying to modify watchscreen.cpp but not working

**Pull request closed without merging**
