### PR TITLE
New/original glyphs for WatchScreen

### PR DESCRIPTION
**Pull request by rparrett**
Here's an alternate set of gylphs for the Watch Screen. I thought that Smoothie could use some graphics that are unique to Smoothie. They come with a modest ~136 byte decrease in flash size.

I plan on looking into improving the look/feel further, but thought I'd test the waters here with a simple PR like this.

Let me know if I've done anything horribly wrong.

glyphs
newglyphs

### CODE REVIEW

**Comment by wolfmanjm** [comment]
looks great... thanks

**Comment by wolfmanjm** [comment]
I just loaded this on my GLCD and the heated bed icon looks really bad, not like the one above at all.

**Comment by rparrett** [comment]
Might be a bug in the "slow pixel by pixel copy" portion of RrdGlcd::renderGlyph. Unfortunately all I have to play with is a Viki2.

**Comment by wolfmanjm** [comment]
the pixels need to be byte aligned for the RRD

**Comment by wolfmanjm** [comment]
I may need to revert this until that is fixed.

**Comment by rparrett** [comment]
I can look a little harder at RrdGlcd::renderGlyph, but probably not tonight. Feel free to revert.

**Comment by rparrett** [comment]
I think that this is a fix:

https://github.com/rparrett/Smoothieware/commit/23c54eb8ae7c94f35e66647e3cdd2e037d874cd7

**Comment by arthurwolf** [comment]
Very nice ! Thanks :)

On Fri, Dec 18, 2015 at 7:51 AM, Rob Parrett <notifications@github.com>
wrote:

> I think that this is a fix:
>
> rparrett@23c54eb
> <https://github.com/rparrett/Smoothieware/commit/23c54eb8ae7c94f35e66647e3cdd2e037d874cd7>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/pull/807#issuecomment-165692632>
> .
>



-- 
Courage et bonne humeur.

**Pull request merged**
