### PR TITLE
Thermistor safety (minimum temperatures)

### PR DESCRIPTION
**Pull request by qharley**
Added a way to specify a minimum temperature to protect against damaged thermistors. If not set, the machine will act as before.

### CODE REVIEW

**Comment by qharley** [comment]
Problems here?

**Comment by wolfmanjm** [comment]
Yea it is not necessary we already check for very low values and handle them here...

https://github.com/RepRapMorgan/Smoothieware/blob/3a014cbbf048d483241d1a7c98f1fc8602e4166c/src/modules/tools/temperaturecontrol/Thermistor.cpp#L95

**Comment by PetteriAimonen** [comment]
This is also discussed in this issue report: https://github.com/Smoothieware/Smoothieware/issues/584

The current check has a few problems:
1) If the thermistor is not 100% broken or if there is a noise on the line, the limit may not activate.
2) As soon as the limit clears, it will start heating again.
3) It does not protect against bad PID config or bad G code.

Myself I run this patch that fully halts on crazy temperatures:
https://github.com/PetteriAimonen/Smoothieware/commit/329be601c91057dbc4926d03b2cc99c534a342c0

IMO it is better to be safe, when there is no real need to handle such excessive temperatures.

**Comment by qharley** [comment]
I have a unique problem that on certain hardware an open circuit thermistor reads -6 volts.
This is a fatal problem, since smoothieware will heat the hot end indefinitely... until a piece melts off of course.

Adding this will protect systems on those smoothie clones, only if configured of course.

**Pull request merged**
