### PR TITLE
Replace Hook with std::function

### PR DESCRIPTION
**Pull request by darthscsi**
Replace Hook with std::function.  Prototypes for callbacks are changed to void(void) since none of the uses of hook either pass arguments or return data.  Some unnecessary indirection is removed in SlowTicker.

### CODE REVIEW

**Comment by wolfmanjm** [comment]
No I tried this, it increases ram usage a lot, so I reverted it.

Thanks for the suggestion though. It would be nice to do if we had unlimited ram available.

**Comment by wolfmanjm** [comment]
Also in future please clean up your PRs so the comits are squashed. It makes it a lot easier to review.

Thanks

**Comment by wolfmanjm** [comment]
I suggest you do a mem before and after and make sure how much RAM your changes use. If it uses less that is great if it uses more and there is no bug fixed, then it must be rejected. We are extremely short on RAM.

**Comment by darthscsi** [comment]
Bind wasn't triggering small-function optimization in std::function.  Lambdas do, however.  See next pull request.

**Pull request closed without merging**
