### PR TITLE
Drills Module (Canned Drilling Cycles Implementation)

### PR DESCRIPTION
**Pull request by lautr3k**
Hello,
Here is my attempt to implement the canned drilling cycles on the Smoothiboard as a module.
At the moment there supporting the following codes : G80-G83, G98, G99 in absolute mode, and in the X/Y plan only. Needs you to test more seriously.

Thank you and sorry for my bad English.

Peace.

### CODE REVIEW

**Comment by arthurwolf** [comment]
drills.dwell_unity should be drills.dwell_units

**Comment by lautr3k** [comment]
Done ;)

**Comment by arthurwolf** [comment]
In the example config file too :)

**Comment by lautr3k** [comment]
Done ;)

**Comment by arthurwolf** [comment]
Thanks ! :) :+1: 

If it's not too much trouble, while you are at it, could you change the module name, both in the code, and in config, from "drills", which does not really match how the other modules are named, to "drillingcycles" ?

Thanks a ton for this :)

**Comment by lautr3k** [comment]
No problem, Done ;) I hope I have made no mistakes

**Comment by arthurwolf** [comment]
Oh by the way, now that this is merged.
Can you document this on the Smoothieware wiki ?
You can enter basic information about what the parameters are, what G-codes it supports, and I'll take care of formating and presentation.
Just ping me here when you have written the wiki page.

Cheers :)

**Comment by lautr3k** [comment]
Yop, 
http://smoothieware.org/drillingcycles

**Pull request merged**
