### PR TITLE
support of configurable slave motors added. 

### PR DESCRIPTION
**Pull request by ytkachov**
any of primary motor (alpha, beta or gamma) can have slave motor which does exactly the same movements as master motor. may be used in shapeoko CNC for Y axes for example.

### CODE REVIEW

**Comment by wolfmanjm** [comment]
Sorry we are not accepting any pull requests for the core kernel at the moment due to an upcoming major refactor.

Please add a link to your fork and a description to this page so others who may need this can use it if they wish..
http://smoothieware.org/third-party-branches

Although I personally prefer the hardware method of accomplishing this particular hack and feel a S/W method is not needed, one of the other core developers may consider merging this at a later date.

Thank you.

**Comment by wolfmanjm** [comment]
As way of discussion in case someone else is interested in this patch I'd also like to add some comments about it.

I do not like the extra memory this uses regardless of whether any motor has slaves.. there are three extra pins per stepper motor whether they are needed or not, this memory usage adds up.
I am also uneasy about the additional work required in a  time critical ISR function to test for, and potentially step, a slave motor. Again the test is required whether or not any slave motors are defined, which in the majority of cases they will not be.

The H/W hack currently used requires no extra memory or processing time.
I am not sure if this could be done in S/W without using extra memory when not in use or extra processing time, but if it could it would be far preferable.

**Comment by qharley** [comment]
I second rather using hardware to do the same.  Missing config could case
serious damage to the system for instance.


  [image: photo]
*Quentin Harley*
Founder, Reprap Morgan 3D Printers
 p:012 004 1883 | m:082 782 3902 | e:quentin@reprapmorgan.com | w:
www.reprapmorgan.com | a: 4 Burger Ave, Lyttelton Manor, Centurion, South
Africa

**Comment by ytkachov** [comment]
Thank all of you for your comments. There were at least two reasons why I decided to do it in software. First of all I am a programmer and do believe that everything which could be done in software must be done in software. The second was that there is such improvement suggested in Smoothie contest page. 

I agree that we could avoid using extra memory and unnecessary test whether or not any slave motors are defined. It is easy. We just need virtual methods and derived class for PairedStepperMotor.

**Comment by arthurwolf** [comment]
Hey !

There is actually a more general way to do this that is useful not only for
axes but also for all other modules : the multipin features, which allows
you to configure pins as "1.31+1.30" for example

Somebody coded it here :
https://github.com/Smoothieware/Smoothieware/compare/edge...gecgooden:fix/slaveaxis

But he doesn't have a Smoothieboard to test it, and when I tested it it did
not work.
If somebody wants to test it and debug it to find what's wrong, it'd be
awesome !

Cheers !


On Sun, Mar 22, 2015 at 12:40 PM, ytkachov <notifications@github.com> wrote:

> Thank all of you for your comments. There were at least two reasons why I
> decided to do it in software. First of all I am a programmer and do believe
> that everything which could be done in software must be done in software.
> The second was that there is such improvement suggested in Smoothie contest
> page.
>
> I agree that we could avoid using extra memory and unnecessary test
> whether or not any slave motors are defined. It is easy. We just need
> virtual methods and derived class for PairedStepperMotor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/pull/643#issuecomment-84589676>
> .
>



-- 
Courage et bonne humeur.

**Comment by ytkachov** [comment]
I can try to understand what is wrong with that solution. It really looks nice and elegant.

**Comment by ytkachov** [comment]
BTW, Arthur what is going on with Smoothie Contest? Looks like page was not updated since long ago...

**Comment by arthurwolf** [comment]
I got many more entries for the contest than I expected, so it's taking me
a long time to process them all, there should be news soon.

On Sun, Mar 22, 2015 at 1:06 PM, ytkachov <notifications@github.com> wrote:

> BTW, Arthur what is going on with Smoothie Contest? Looks like page was
> not updated since long ago...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/pull/643#issuecomment-84593278>
> .
>



-- 
Courage et bonne humeur.

**Comment by ytkachov** [comment]
Hi Arthur,

I have investigated source codes of 

https://github.com/Smoothieware/Smoothieware/compare/edge...gecgooden:fix/slaveaxis

Though idea is very elegant its implementation is completely incorrect. It appears that this approach just can't work as it was supposed to work. Besides strange things like this:

    Pin* Pin::from_string(std::string value) {
        SinglePin* s_pin = new SinglePin();  // new SinglePin gets created
        s_pin->from_string(value); 	         // and initialized from string
                                             // and... nothing...
        return this;
    }

the main problem is that in many classes (StepperMotor, Extruder, ReprapDiscountGLCD and others) Pin is used as an *object*, not a *pointer to object*. As a result it can't be "virtualized" that is we can't use DoublePin as Pin. There are three possible solutions:

1) each Pin has information about two physical pins and some property which tell us if it is Single or Double. It is easy to implement but leads to waste of memory in all cases while Double Pins will be used quite rare.

2) Replace all Pin object to pointers to Pin. Though it requires changes in many places this approach is most robust. Additional memory is used when it is really required, correspond to general coding rules (for example in the Robot class there is pointer to StepperMotor objects while Pins are present as objects which means that header must be included in header). Drawbacks of this way is: a) using of inline functions becomes impossible b) call of virtual method requires additional processor time which may be critical.

3) Pin object is thin wrapper around internal pin_impl which is stored as pointer. pin_impl could be SinglePin or DoublePin depending on initialization string. In this case no changes required in those classes which use Pin obects but again more processor time waste on virtual method calls and additinal pointer is stored in Pin object.

_Which approach is preferable? Sorry for asking but having 20+ years of C++ Desktop and server development I am quite new in embedded programming so I need some advice to make it correct._

Thanks

**Comment by arthurwolf** [comment]
Hey !

I think the best method here would be number 2.
But it needs to be tested for performance once implemented, as we can't
afford to loose too much time on some operations.

Cheers !


On Wed, Mar 25, 2015 at 1:20 PM, ytkachov <notifications@github.com> wrote:

> Hi Arthur,
>
> I have investigated source codes of
>
> edge...gecgooden:fix/slaveaxis
> <https://github.com/Smoothieware/Smoothieware/compare/edge...gecgooden:fix/slaveaxis>
>
> Though idea is very elegant its implementation is completely incorrect. It
> appears that this approach just can't work as it was supposed to work.
> Besides strange things like this:
>
> Pin* Pin::from_string(std::string value) {
>     SinglePin* s_pin = new SinglePin();  // new SinglePin gets created
>     s_pin->from_string(value);           // and initialized from string
>                                          // and... nothing...
>     return this;
> }
>
> the main problem is that in many classes (StepperMotor, Extruder,
> ReprapDiscountGLCD and others) Pin is used as an *object*, not a *pointer
> to object*. As a result it can't be "virtualized" that is we can't use
> DoublePin as Pin. There are three possible solutions:
>
> 1) each Pin has information about two physical pins and some property
> which tell us if it is Single or Double. It is easy to implement but leads
> to waste of memory in all cases while Double Pins will be used quite rare.
>
> 2) Replace all Pin object to pointers to Pin. Though it requires changes
> in many places this approach is most robust. Additional memory is used when
> it is really required, correspond to general coding rules (for example in
> the Robot class there is pointer to StepperMotor objects while Pins are
> present as objects which means that header must be included in header).
> Drawbacks of this way is: a) using of inline functions becomes impossible
> b) call of virtual method requires additional processor time which may be
> critical.
>
> 3) Pin object is thin wrapper around internal pin_impl which is stored as
> pointer. pin_impl could be SinglePin or DoublePin depending on
> initialization string. In this case no changes required in those classes
> which use Pin obects but again more processor time waste on virtual method
> calls and additinal pointer is stored in Pin object.
>
> *Which approach is preferable? Sorry for asking but having 20+ years of
> C++ Desktop and server development I am quite new in embedded programming
> so I need some advice to make it correct.*
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/pull/643#issuecomment-86002549>
> .
>



-- 
Courage et bonne humeur.

**Comment by wolfmanjm** [comment]
The trouble is making pins virtual will also add more memory overhead as that will make the vtable bigger for everything that uses a pin. Plus there will be a pointer to a pin plus the actual pin itself.
Why do we need this when there is a perfectly acceptable way to do it by wiring?

**Comment by arthurwolf** [comment]
On Wed, Mar 25, 2015 at 7:59 PM, Jim Morris <notifications@github.com>
wrote:

> The trouble is making pins virtual will also add more memory overhead as
> that will make the vtable bigger for everything that uses a pin. Plus there
> will be a pointer to a pin plus the actual pin itself.
> Why do we need this when there is a perfectly acceptable way to do it by
> wiring?
>

It's a feature lots of people have been asking for.
But if it can't be done without a big RAM cost, it shouldn't be done.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smoothieware/Smoothieware/pull/643#issuecomment-86173592>
> .
>



-- 
Courage et bonne humeur.

**Pull request closed without merging**
