### PR TITLE
rectangular z grid probe

### PR DESCRIPTION
**Pull request by wolfmanjm**
as per PR #1116

### CODE REVIEW

**Comment by pflugj** [comment]
I have tested this new "cartesian-grid" and it seems to do the job ;-)
...well done and thanks ;-)

However I must say that I kind of liked to set the origin to the center. 
I built a pretty big CoreXY machine (>50x50x40) and 
I let the machine do a grid-leveling before every print.
The built platform is some 8.4mm security glass and should be pretty straight.
 
With the setting of the orgin to the center I usually did only a 30x30cm grid with 3x3 points
With the new "cartesian-grid" I have to set the Origin to the bottom left, to get the grid to work 
and have to run the full size grid over at least 45x45cm and therefore I also selected more grid points (5x5).

Maybe it is still possible to do the center setup with the cartesian ?
and do the cartesian-grid from the center?  

.. or do I miss something as usuall?

Thanks again
Jürgen

**Comment by qharley** [comment]
We had it in Zgrid. Easy addition

**Comment by wolfmanjm** [comment]
You can still set center 0,0 if you prefer that. the issue is what the machine coordinates are set to, and those need to be 0,0 in corner left. To set 0,0 center just set up WCS (as explained in the wiki) the scan will still scan the entire grid though starting at 0,0. 
You setup WCS with either G92 or G10 L2 or L20.
The scan size can be changed using the X and Y parameters to the G31, but will be relative to the 0,0 in machine coordinates as scans are always performed in machine coordinates.
If you really want 0,0 in the center then use delta grid, it will still works, although the is_square has been deprecated.
It is not easy to go back to using 0,0 as the center in the new rectangular grid so i don't think we will be doing that, it was a specific request we eliminate that requirement.

**Comment by wolfmanjm** [comment]
FWIW there is no reason to run a grid scan every print, that is why we allow it to be saved and reloaded.

Also if you have a flat bed then there is no reason to use a grid at all you should use the threepoint leveling as that is far more efficient and does not slow the entire system down during a print. whereas zgrid will slow down due to the 1mm segmentation required.

**Pull request merged**
