### PR TITLE
Add two parameters for pannel

### PR DESCRIPTION
**Pull request by cxandy**
Add two parameters for pannel:
rough_contrast ; support more st7565 diaplay
is_sh1106 ; support oled 1.3"

### CODE REVIEW

**Comment by wolfmanjm** [comment]
There is already a sh1106 PR is that not enough? as this will conflict with that.

**Comment by cxandy** [comment]
already is ssd1306_oled not sh1106.

**Comment by wolfmanjm** [comment]
look at #1142

**Comment by wolfmanjm** [comment]
closed as duplicate of #1142

**Pull request closed without merging**
