### PR TITLE
CoreXZ Support

### PR DESCRIPTION
**Pull request by jnjackins**
I've added support for CoreXZ style 3D printers (http://forums.reprap.org/read.php?2,377858)

I''d be happy to contribute the changes upstream. Please have a look and tell me what you think of my approach.

Another approach would be to integrate the CoreXZSolution code with the HBotSolution code with a configuration option such as hbot_motion_plane, letting users choose an XY configuration for HBot or CoreXY style machines, and XZ for CoreXZ style machines. This would reduce duplicate/similar code, but also add complexity.

### CODE REVIEW

**Comment by wolfmanjm** [comment]
This look fine except rather than provide a whole new config file, just provide the few lines of config and put it in the Snippets directory.

**Comment by wolfmanjm** [comment]
Also maybe you should add options settable by M665 like the delta solution does to give an alternative for setting the reduction configuration.

**Comment by jnjackins** [comment]
Re: M665 - I'm not sure there's much point. These reduction values aren't something that ever needs calibration or adjustment; they should always be round numbers that are fundamental to the design of the machine. If you feel strongly about it, though, I can add it.

**Comment by wolfmanjm** [comment]
ok no problem, just remove the sample config, and create a snippet instead. 
Thanks

**Comment by jnjackins** [comment]
Already done :)

**Pull request merged**
